/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/23T9tkqdi1g
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { CardTitle, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import Link from "next/link"
import { Button } from "@/components/ui/button"

export default function Insurance() {
  return (
    <main className="w-full max-w-7xl mx-auto py-12 px-4 md:px-6">
      <div className="space-y-6">
        <div className="space-y-2">
          <h1 className="text-3xl font-bold tracking-tighter md:text-4xl">Compare Health Insurance Plans</h1>
          <p className="text-gray-500 dark:text-gray-400">Find the best health insurance plan for your needs.</p>
        </div>
        <div className="grid grid-cols-1 gap-6 max-w-xxl">
          <Card>
            <CardHeader>
              <CardTitle>SBI Arogya Supreme</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-4">
                <div className="flex items-center justify-between">
                  <span className="text-gray-500 dark:text-gray-400">Coverage</span>
                  <span className="font-medium">₹5 Lakh</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-gray-500 dark:text-gray-400">Duration</span>
                  <div className="flex gap-2">
                    <span className="font-medium">1 year</span>
                    <span className="font-medium">2 years</span>
                    <span className="font-medium">3 years</span>
                  </div>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-gray-500 dark:text-gray-400">Premium</span>
                  <div className="flex gap-2">
                    <span className="font-medium">₹10,083</span>
                    <span className="font-medium">₹19,166</span>
                    <span className="font-medium">₹25,208</span>
                  </div>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-gray-500 dark:text-gray-400">Savings</span>
                  <div className="flex gap-2">
                    <span className="font-medium">₹841</span>
                    <span className="font-medium">₹1,597</span>
                    <span className="font-medium">₹2,101</span>
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-2">
                <div className="flex items-center gap-2">
                  <CheckIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
                  <span>93.3% of claims paid within 3 months†</span>
                </div>
                <div className="flex items-center gap-2">
                  <CheckIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
                  <span>Single pvt AC Room</span>
                </div>
                <div className="flex items-center gap-2">
                  <CheckIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
                  <span>₹75,000 No Claim Bonus</span>
                </div>
                <div className="flex items-center gap-2">
                  <CheckIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
                  <span>Restoration of cover once a year</span>
                </div>
                <Link className="text-blue-600 underline" href="#">
                  View all features ›
                </Link>
              </div>
            </CardContent>
            <CardFooter>
              <Button className="w-full">Add to compare</Button>
            </CardFooter>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>ICICI Lombard - Health AdvantEdge</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-4">
                <div className="flex items-center justify-between">
                  <span className="text-gray-500 dark:text-gray-400">Coverage</span>
                  <span className="font-medium">₹10 Lakh</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-gray-500 dark:text-gray-400">Duration</span>
                  <div className="flex gap-2">
                    <span className="font-medium">1 year</span>
                    <span className="font-medium">2 years</span>
                    <span className="font-medium">3 years</span>
                  </div>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-gray-500 dark:text-gray-400">Premium</span>
                  <div className="flex gap-2">
                    <span className="font-medium">₹10,117</span>
                    <span className="font-medium">₹19,234</span>
                    <span className="font-medium">₹25,292</span>
                  </div>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-gray-500 dark:text-gray-400">Savings</span>
                  <div className="flex gap-2">
                    <span className="font-medium">₹844</span>
                    <span className="font-medium">₹1,602</span>
                    <span className="font-medium">₹2,108</span>
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-2">
                <div className="flex items-center gap-2">
                  <CheckIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
                  <span>97.1% of claims paid within 3 months†</span>
                </div>
                <div className="flex items-center gap-2">
                  <CheckIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
                  <span>
                    Get coverage for doctor consultation fees, pharmacy cover, medical tests, physiotherapy, and more
                    without hospitalisation with BeFit rider
                  </span>
                </div>
                <div className="flex items-center gap-2">
                  <CheckIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
                  <span>Single pvt AC Room</span>
                </div>
                <div className="flex items-center gap-2">
                  <CheckIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
                  <span>₹2 lakh Renewal Bonus</span>
                </div>
                <div className="flex items-center gap-2">
                  <CheckIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
                  <span>Unlimited Restoration of cover</span>
                </div>
                <Link className="text-blue-600 underline" href="#">
                  View all features ›
                </Link>
              </div>
            </CardContent>
            <CardFooter>
              <Button className="w-full">Add to compare</Button>
            </CardFooter>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Niva Bupa (formerly known as Max Bupa) - Aspire Gold+ (Direct)</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-4">
                <div className="flex items-center justify-between">
                  <span className="text-gray-500 dark:text-gray-400">Coverage</span>
                  <span className="font-medium">₹5 Lakh</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-gray-500 dark:text-gray-400">Duration</span>
                  <div className="flex gap-2">
                    <span className="font-medium">1 year</span>
                    <span className="font-medium">2 years</span>
                    <span className="font-medium">3 years</span>
                  </div>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-gray-500 dark:text-gray-400">Premium</span>
                  <div className="flex gap-2">
                    <span className="font-medium">₹12,000</span>
                    <span className="font-medium">₹22,000</span>
                    <span className="font-medium">₹30,000</span>
                  </div>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-gray-500 dark:text-gray-400">Savings</span>
                  <div className="flex gap-2">
                    <span className="font-medium">₹1,000</span>
                    <span className="font-medium">₹2,000</span>
                    <span className="font-medium">₹3,000</span>
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-2">
                <div className="flex items-center gap-2">
                  <CheckIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
                  <span>99.1% of claims paid within 3 months†</span>
                </div>
                <div className="flex items-center gap-2">
                  <CheckIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
                  <span>Inclusive of 5% direct discount*</span>
                </div>
                <div className="flex items-center gap-2">
                  <CheckIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
                  <span>Get maternity coverage for both mother & new born baby</span>
                </div>
                <div className="flex items-center gap-2">
                  <CheckIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
                  <span>No Room Rent Limit</span>
                </div>
                <div className="flex items-center gap-2">
                  <CheckIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
                  <span>₹5 lakh No Claim Bonus</span>
                </div>
                <div className="flex items-center gap-2">
                  <CheckIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
                  <span>Unlimited Restoration of Cover,Forever</span>
                </div>
              </div>
            </CardContent>
            <CardFooter>
              <Button className="w-full">Add to compare</Button>
            </CardFooter>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Raheja QBE - Health QuBE Basic</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-4">
                <div className="flex items-center justify-between">
                  <span className="text-gray-500 dark:text-gray-400">Coverage</span>
                  <span className="font-medium">₹5 Lakh</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-gray-500 dark:text-gray-400">Duration</span>
                  <div className="flex gap-2">
                    <span className="font-medium">1 year</span>
                    <span className="font-medium">2 years</span>
                    <span className="font-medium">3 years</span>
                  </div>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-gray-500 dark:text-gray-400">Premium</span>
                  <div className="flex gap-2">
                    <span className="font-medium">₹237</span>
                    <span className="font-medium">₹2,843</span>
                    <span className="font-medium">₹2,843</span>
                  </div>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-gray-500 dark:text-gray-400">Savings</span>
                  <div className="flex gap-2">
                    <span className="font-medium">₹20</span>
                    <span className="font-medium">₹237</span>
                    <span className="font-medium">₹237</span>
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-2">
                <div className="flex items-center gap-2">
                  <CheckIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
                  <span>93.3% of claims paid within 3 months†</span>
                </div>
                <div className="flex items-center gap-2">
                  <CheckIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
                  <span>Room rent limit is ₹5000/day</span>
                </div>
                <div className="flex items-center gap-2">
                  <CheckIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
                  <span>₹25,000 No Claim Bonus</span>
                </div>
                <div className="flex items-center gap-2">
                  <CheckIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
                  <span>Restoration of cover once a year</span>
                </div>
                <Link className="text-blue-600 underline" href="#">
                  View all features ›
                </Link>
              </div>
            </CardContent>
            <CardFooter>
              <Button className="w-full">Add to compare</Button>
            </CardFooter>
          </Card>
          <Card>
            <CardHeader>
              <CardTitle>Care Health Care Supreme Direct</CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
              <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-4">
                <div className="flex items-center justify-between">
                  <span className="text-gray-500 dark:text-gray-400">Coverage</span>
                  <span className="font-medium">₹5 Lakh</span>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-gray-500 dark:text-gray-400">Duration</span>
                  <div className="flex gap-2">
                    <span className="font-medium">1 year</span>
                    <span className="font-medium">2 years</span>
                    <span className="font-medium">3 years</span>
                  </div>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-gray-500 dark:text-gray-400">Premium</span>
                  <div className="flex gap-2">
                    <span className="font-medium">₹14,000</span>
                    <span className="font-medium">₹26,000</span>
                    <span className="font-medium">₹35,000</span>
                  </div>
                </div>
                <div className="flex items-center justify-between">
                  <span className="text-gray-500 dark:text-gray-400">Savings</span>
                  <div className="flex gap-2">
                    <span className="font-medium">₹1,000</span>
                    <span className="font-medium">₹2,000</span>
                  </div>
                </div>
              </div>
              <div className="flex flex-col gap-2">
                <div className="flex items-center gap-2">
                  <CheckIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
                  <span>93.3% of claims paid within 3 months†</span>
                </div>
                <div className="flex items-center gap-2">
                  <CheckIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
                  <span>Room rent limit is ₹5000/day</span>
                </div>
                <div className="flex items-center gap-2">
                  <CheckIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
                  <span>₹25,000 No Claim Bonus</span>
                </div>
                <div className="flex items-center gap-2">
                  <CheckIcon className="w-4 h-4 fill-gray-900 dark:fill-gray-50" />
                  <span>Restoration of cover once a year</span>
                </div>
                <Link className="text-blue-600 underline" href="#">
                  View all features ›
                </Link>
              </div>
            </CardContent>
            <CardFooter>
              <Button className="w-full">Add to compare</Button>
            </CardFooter>
          </Card>
        </div>
      </div>
    </main>
  )
}

function CheckIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M20 6 9 17l-5-5" />
    </svg>
  )
}
