/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/pvpKuqSGM28
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { IBM_Plex_Sans } from 'next/font/google'

ibm_plex_sans({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { CardTitle, CardDescription, CardHeader, CardContent, CardFooter, Card } from "@/components/ui/card"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"

export default function Login() {
  return (
    <div className="flex min-h-[100dvh] w-full items-center justify-center bg-gradient-to-r from-[#0077B6] to-[#00A8E8] px-4 py-12 md:px-6 lg:py-24">
      <div className="mx-auto flex w-full max-w-[900px] flex-col items-center justify-between gap-8 rounded-xl bg-white p-6 shadow-lg md:flex-row md:p-12">
        <div className="flex-1 space-y-4">
          <h1 className="text-3xl font-bold tracking-tight text-gray-900 sm:text-4xl md:text-5xl">
            Welcome to MedCare
          </h1>
          <p className="text-lg text-gray-600">Providing exceptional healthcare services to our community.</p>
          <div className="relative group">
            <img
              alt="Healthcare Hero"
              className="mx-auto rounded-lg object-cover md:mx-0 group-hover:scale-105 transition-transform duration-300 ease-in-out"
              height={400}
              src="/placeholder.svg"
              style={{
                aspectRatio: "500/400",
                objectFit: "cover",
              }}
              width={500}
            />
            <div className="absolute inset-0 bg-black/50 rounded-lg opacity-0 group-hover:opacity-100 transition-opacity duration-300 ease-in-out flex items-center justify-center">
              <Button
                className="animate-bounce hover:scale-105 transition-transform duration-300 ease-in-out"
                size="lg"
                variant="primary"
              >
                Explore Services
              </Button>
            </div>
          </div>
        </div>
        <div className="flex-1 space-y-4">
          <Card className="w-full max-w-md bg-gray-50 dark:bg-gray-800 border border-gray-200 dark:border-gray-700 shadow-lg dark:border-gray-800">
            <CardHeader className="space-y-1 p-6">
              <CardTitle className="text-2xl font-bold">Login to your account</CardTitle>
              <CardDescription className="text-gray-500 dark:text-gray-400">
                Enter your credentials to access your MedCare account.
              </CardDescription>
            </CardHeader>
            <CardContent className="space-y-4 p-6">
              <div className="grid gap-2">
                <Label className="font-medium" htmlFor="username">
                  Username
                </Label>
                <Input
                  className="animate-[wiggle_0.5s_ease-in-out] hover:animate-[wiggle_0.5s_ease-in-out] focus:ring-2 focus:ring-[#0077B6] focus:border-[#0077B6] dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 hover:border-[#0077B6] transition-colors duration-300 ease-in-out"
                  id="username"
                  placeholder="Enter your username"
                  type="text"
                />
              </div>
              <div className="grid gap-2">
                <Label className="font-medium" htmlFor="password">
                  Password
                </Label>
                <Input
                  className="animate-[wiggle_0.5s_ease-in-out] hover:animate-[wiggle_0.5s_ease-in-out] focus:ring-2 focus:ring-[#0077B6] focus:border-[#0077B6] dark:bg-gray-700 dark:text-white dark:placeholder-gray-400 hover:border-[#0077B6] transition-colors duration-300 ease-in-out"
                  id="password"
                  placeholder="Enter your password"
                  type="password"
                />
              </div>
            </CardContent>
            <CardFooter className="p-6">
              <Button
                className="w-full animate-[bounce_1s_ease-in-out] hover:animate-[bounce_1s_ease-in-out] hover:scale-105 transition-transform duration-300 ease-in-out"
                variant="primary"
              >
                Login
              </Button>
            </CardFooter>
          </Card>
        </div>
      </div>
    </div>
  )
}
